apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: my-api
  description: My API description
spec:
  type: openapi
  lifecycle: production
  owner: guests
  definition:
    $text: ./openapi.yaml
