apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: my-api
  description: "API cho backend"
  tags:
    - rest
spec:
  type: openapi
  lifecycle: production
  owner: team-a
  system: my-system
  definition:
    $text: |
      openapi: 3.0.0
      info:
        title: My API
        version: 1.0.0
      paths: {}
